# 빅데이터 코딩 3주차

## 1) numpy module (배열, 수치계산)

In [3]:
import numpy as np

#numpy 모듈은 다차원 배열을 다루는 함수임

In [5]:
# 1차원 배열 -> list가 아닌 numpy.ndarray 타입임
# so , list 타입을 사용하려면 형변환이 필요함

a = np.array([1,2,3,4,5])
print(a,type(a))


[1 2 3 4 5] <class 'numpy.ndarray'>


In [11]:
# 2차원 배열
b = np.array([[1,3,5],[2,4,6]])
print(b)

[[1 3 5]
 [2 4 6]]


In [14]:
# 3차원 배열
c = np.array([[[1,3],[2,4]],[[5,6],[4,1]]])
print(c)

[[[1 3]
  [2 4]]

 [[5 6]
  [4 1]]]


In [23]:
# 3X5 3열 5행
#np array
d = np.array([[1,2,3,4,5],\
            [2,4,6,7,8],\
            [5,6,7,8,9]])

#list
list_ = [[1,2,3,4,5],\
        [2,4,6,7,8],\
        [5,6,7,8,9]]

print(d[2][1:3])

print(d[2,3])

print(list_[2][3])

[6 7]
8
8


In [24]:
# shape : 배열의 크기
# np.shape()
print(d.shape)
# (n행, m열)

(3, 5)


In [31]:
# dtype() : 배열 원소 자료형 확인
# int (32/64) bit
# float (32/64)
# bool
# string

# 서로 다른 형태가 들어가있는 배열
e = np.array([1,3.2,'string'])
print(e)

# 같은 타입
e1 = np.array([3.2,4.2])
print(e1)

e2 = np.array(['one','two','three'])

# U5 : 유니코드 5
print(e2.dtype)

# U32 : 유니코드 32
print(e.dtype)

print(e1.dtype)

['1' '3.2' 'string']
[3.2 4.2]
<U5
<U32
float64


In [36]:
# 배열 유형 바꾸기
# astype() : 임시 형 변환

g = np.array([1,2])
print(g.dtype)
print(g)

k = g.astype('float64')
print(k.dtype)
print(k)

int32
[1 2]
float64
[1. 2.]


In [37]:
# numpy의 배열 만드는 함수
# zeros(n행,m열) : 0으로 이루어진 배열

a = np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [39]:
# ones() : 1로 이루어진 배열

b = np.ones([2,3])
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]


In [41]:
# arange(2,10)
# 2-9까지 이루어진 배열

c = np.arange(2,10)
print(c)

[2 3 4 5 6 7 8 9]


In [48]:
# transpose() 
# 행 열 전환
d = np.array([[1,2,3],[4,5,6]])
print(d)
print(np.transpose(d))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [57]:
# array 연산
arr1 = np.array([[1,2,3]\
                ,[4,5,6]])
arr2 = np.array([[11,12,13]\
                ,[14,15,16]])

# +/- 는 일반적인
print(arr1+arr2)
print(arr1-arr2)

# 일반적인 곱셈이 아니라 행렬의 곱임.
print(arr1*arr2)

#서로 다른 크기의 행렬 더하기
arr3 = np.array([100,200,300])
print(arr1+arr3)


[[12 14 16]
 [18 20 22]]
[[-10 -10 -10]
 [-10 -10 -10]]
[[11 24 39]
 [56 75 96]]
[[101 202 303]
 [104 205 306]]


In [65]:
# slice
a_list = [[1,2,3,4,5],[6,7,8,9,10],[5,7,9,10,2]]
a = np.array([[1,2,3,4,5],[6,7,8,9,10],[5,7,9,10,2]])
print(a_list[2][1])

a_list[2][1] = 1

print(a_list[2][1])

print(a)
a[:2] = 1
print(a)

7
1
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 5  7  9 10  2]]
[[ 1  1  1  1  1]
 [ 1  1  1  1  1]
 [ 5  7  9 10  2]]


## 2) pandas module (통계 분석)

In [5]:
!pip list

Package            Version
------------------ -----------
astroid            2.5.1
asttokens          2.2.1
backcall           0.2.0
beautifulsoup4     4.11.1
bs4                0.0.1
certifi            2022.9.24
charset-normalizer 2.1.1
colorama           0.4.4
comm               0.1.2
debugpy            1.6.4
decorator          5.1.1
entrypoints        0.4
executing          1.2.0
idna               3.4
ipykernel          6.19.4
ipython            8.7.0
isort              5.7.0
jedi               0.18.2
jupyter_client     7.4.8
jupyter_core       5.1.1
lazy-object-proxy  1.5.2
matplotlib-inline  0.1.6
mccabe             0.6.1
nest-asyncio       1.5.6
numpy              1.24.1
packaging          22.0
pandas             1.5.2
parso              0.8.3
pickleshare        0.7.5
platformdirs       2.6.0
prompt-toolkit     3.0.36
psutil             5.9.4
pure-eval          0.2.2
Pygments           2.13.0
pylint             2.7.2
python-dateutil    2.8.2
pytz               2022.7
pywin32    

You should consider upgrading via the 'C:\Users\조민근\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip' command.


In [6]:
import pandas as pd

In [7]:
# 1. 딕셔너리(사전형) 만들기
data = {'name ' : {'Mark','Jane','Chris','Ryan'},\
        'age' : {33,32,35,42},\
        'score' : {91.2,83.4,77.5,87.7}}

In [14]:
#Dataframe
df = pd.DataFrame(data)
print(type(df))

TypeError: 'set' type is unordered

In [12]:
# sum() : 합계
print('합계 - \n', df.sum())

NameError: name 'df' is not defined

In [ ]:
# mean() : 평균
print('평균 - \n', df.mean())

In [ ]:
# 데이터 선택하기
print(df.name)
print(df['name'])

In [ ]:
# read_csv() csv file을 dataframe으로 바꿔주는 함수
df = pd.read_csv('./class3/apt.csv',encoding='cp949')
print(df)

In [ ]:
# head() : 상단 부분만 선택해서 출력
print(df.head())

# tail() : 하단 부분만 선택해서 출력
print(df.tail())

In [ ]:
print(df.지역)
print(df['지역'])

In [ ]:
#조건 별로 출력하기

# 조건 확인(T/F)
print(df.면적 > 50)

# 조건에 맞는 정보 추출
print(df[df.면적>130])

In [ ]:
#여러개의 조건

# AND : &
print([(df.면적>130) & (df.가격 <=15000)])

# OR : |
print([(df.면적>130) | (df.가격 <=15000)]) 

In [ ]:
#df.loc [원하는 행의 조건, 원하는 열의 조건]
print(df.loc[:10,['아파트','가격']])

print(df.loc[:10,['아파트','가격']][(df.면적>130)]&[(df.가격<15000)])


In [11]:
# 가격이 40000을 초과하는 아파트, 가격을 출력하세요
print(df.loc[: ,['아파트','가격']][df.가격<15000])


NameError: name 'df' is not defined